# Generated by Django 3.2.4 on 2021-06-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210623_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True, max_length=150, verbose_name='title'),
        ),
    ]
