# Generated by Django 3.2.4 on 2021-08-17 10:52

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Tag')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.TextField(blank=True, max_length=150, verbose_name='title')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=posts.models.user_directory_path, verbose_name='Image')),
                ('caption', models.TextField(blank=True, max_length=1500, verbose_name='Caption')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(related_name='tags', to='posts.Tag')),
            ],
            options={
                'ordering': ['-posted'],
            },
        ),
    ]
