# Generated by Django 3.2.4 on 2021-08-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user__picture'),
        ('users', '0012_alter_user__picture'),
    ]

    operations = [
    ]
