# Generated by Django 3.2.4 on 2021-09-01 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_tododata_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 9, 2, 35, 856971)),
        ),
    ]
