# Generated by Django 3.2.4 on 2021-08-02 10:12

from django.db import migrations, models
import gdstorage.storage
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=users.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
