# Generated by Django 3.2.4 on 2021-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('users', '0002_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='profile', to='posts.Post'),
        ),
    ]
