# Generated by Django 3.2.4 on 2021-06-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
