# Generated by Django 3.2.4 on 2021-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='tp',
            field=models.IntegerField(default=0),
        ),
    ]
