# Generated by Django 3.2.4 on 2021-08-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow_tp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='tp',
        ),
    ]
