# Generated by Django 3.2.4 on 2021-08-15 17:41

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_follow_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='https://www.computerhope.com/jargon/g/guest-user.jpg', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', verbose_name='Picture'),
        ),
    ]
