# Generated by Django 3.2.4 on 2021-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
