# Generated by Django 3.2.4 on 2021-08-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='room_id',
            new_name='room_name',
        ),
    ]
