<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-08-09 14:32
=======
# Generated by Django 3.2.4 on 2021-08-09 13:53
>>>>>>> 093e3ca9182d534e44a40310c2c687f149fddbfa

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_room_id_chat_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-created_at',)},
        ),
    ]
