# Generated by Django 3.2.4 on 2021-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20210810_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentchat',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
