# Generated by Django 3.2.4 on 2021-08-10 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_recentchat_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentchat',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='recentchat',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recentchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
