# Generated by Django 3.2.4 on 2021-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_recentchat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentchat',
            name='room_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
