# Generated by Django 3.2.4 on 2021-08-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_ago',
            field=models.CharField(default=models.DateTimeField(auto_now_add=True), max_length=90),
        ),
    ]
