# Generated by Django 3.2.4 on 2021-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_time_ago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_ago',
            field=models.CharField(default='now', max_length=90),
        ),
    ]
