# Generated by Django 3.2.4 on 2021-08-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_time_ago'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_ago',
            field=models.CharField(default='get_date', max_length=90),
        ),
    ]
