# Generated by Django 3.2.4 on 2021-08-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_time_ago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='time_ago',
        ),
    ]
