# Generated by Django 3.2.4 on 2021-08-09 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_likes_unique_together'),
        ('comments', '0003_comment_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'post')},
        ),
    ]
